name = input("Name: ")
address = input("Address: ")
nim = int(input("NIM: "))
phone = input("Phone Number: ")
prodi = input("prodi: ")
print("========================================")
print("Name:"+name)
print("Address:"+address)
print("NIM:",nim)
print("Phone:"+phone)
print("prodi: "+prodi)
print("========================================")